apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgres-configmap.yaml
- postgres-pvc.yaml
- postgres-statefulset.yaml
- postgres-service.yaml

commonLabels:
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: llm-cost-ops
